/**
 * Canonical device contracts for the Aveum energy platform.
 *
 * These types normalize hardware-specific APIs into a single shape the
 * optimizer and control loop can reason about safely.
 */

export type DeviceKind =
  | "solar_inverter"
  | "battery"
  | "ev_charger"
  | "smart_meter"
  | "gateway";

export type DeviceConnectionStatus =
  | "online"
  | "offline"
  | "degraded"
  | "unauthorized"
  | "unknown";

export type DeviceCommandType =
  | "start_charging"
  | "stop_charging"
  | "set_mode"
  | "set_power_limit"
  | "set_target_soc"
  | "set_reserve_soc"
  | "schedule_window"
  | "refresh_state";

export type DeviceMode =
  | "auto"
  | "charge"
  | "discharge"
  | "export"
  | "hold"
  | "eco"
  | "boost"
  | "stop";

export type CommandStatus =
  | "accepted"
  | "scheduled"
  | "executed"
  | "rejected"
  | "failed";

export type DeviceCapability =
  | "read_power"
  | "read_energy"
  | "read_soc"
  | "read_tariff"
  | "start_stop"
  | "set_mode"
  | "set_target_soc"
  | "set_reserve_soc"
  | "set_power_limit"
  | "schedule_window";

/**
 * Generic time window used for planned control actions.
 */
export interface TimeWindow {
  startAt: string;
  endAt: string;
}

/**
 * Normalized per-device telemetry used throughout the system.
 */
export interface DeviceState {
  /** Stable internal ID used by Aveum across UI, control, and analytics. */
  deviceId: string;
  /** High-level device category used by the optimizer. */
  kind: DeviceKind;
  /** Vendor or integration provider name, for example Tesla or GivEnergy. */
  brand: string;
  /** Human-friendly label shown in operations tooling and the UI. */
  name: string;
  /** Current connectivity state of the adapter. */
  connectionStatus: DeviceConnectionStatus;
  /** Timestamp of the most recent successfully synced telemetry sample. */
  lastUpdatedAt: string;
  /** Optional vendor model name when known. */
  model?: string;
  /** Optional serial or provider-side identifier. */
  externalId?: string;
  /** Supported control and telemetry features for this device. */
  capabilities: DeviceCapability[];
  /** Current instantaneous power reading. Positive values mean device output. */
  powerW?: number;
  /** Energy recorded today for this device, when available. */
  energyTodayKwh?: number;
  /** Battery or EV state of charge, normalized to percent. */
  stateOfChargePercent?: number;
  /** Total usable capacity for storage-capable devices. */
  capacityKwh?: number;
  /** Current charge or discharge mode reported by the vendor. */
  mode?: DeviceMode;
  /** Whether an EV charger has a vehicle physically connected. */
  connected?: boolean;
  /** Site-level import or export power for grid-connected devices. */
  gridPowerW?: number;
  /** Home load associated with the device or gateway, when available. */
  homeLoadW?: number;
  /** Free-form, typed-safe metadata for vendor-specific attributes. */
  metadata?: Record<string, string | number | boolean | null>;
}

interface BaseDeviceCommand {
  /** Stable command ID generated by Aveum for traceability. */
  commandId: string;
  /** Target normalized device ID. */
  deviceId: string;
  /** When Aveum issued the command. */
  issuedAt: string;
  /** Why the command was issued, for explainability and audit trails. */
  reason?: string;
  /** Optional scheduling window for commands that should not execute immediately. */
  effectiveWindow?: TimeWindow;
}

export interface StartChargingCommand extends BaseDeviceCommand {
  type: "start_charging";
}

export interface StopChargingCommand extends BaseDeviceCommand {
  type: "stop_charging";
}

export interface SetModeCommand extends BaseDeviceCommand {
  type: "set_mode";
  mode: DeviceMode;
}

export interface SetPowerLimitCommand extends BaseDeviceCommand {
  type: "set_power_limit";
  powerW: number;
}

export interface SetTargetSocCommand extends BaseDeviceCommand {
  type: "set_target_soc";
  targetSocPercent: number;
}

export interface SetReserveSocCommand extends BaseDeviceCommand {
  type: "set_reserve_soc";
  reserveSocPercent: number;
}

export interface ScheduleWindowCommand extends BaseDeviceCommand {
  type: "schedule_window";
  window: TimeWindow;
  targetMode?: DeviceMode;
}

export interface RefreshStateCommand extends BaseDeviceCommand {
  type: "refresh_state";
}

/**
 * Strongly typed command union dispatched by the control loop.
 */
export type DeviceCommand =
  | StartChargingCommand
  | StopChargingCommand
  | SetModeCommand
  | SetPowerLimitCommand
  | SetTargetSocCommand
  | SetReserveSocCommand
  | ScheduleWindowCommand
  | RefreshStateCommand;

/**
 * Normalized result returned by a device adapter after command execution.
 */
export interface CommandResult {
  /** The originating Aveum command ID. */
  commandId: string;
  /** Device that received the command. */
  deviceId: string;
  /** Adapter-side execution outcome. */
  status: CommandStatus;
  /** Indicates whether the provider accepted the request. */
  accepted: boolean;
  /** Timestamp when the provider acknowledged or executed the command. */
  completedAt: string;
  /** Optional provider-side command ID or job reference. */
  providerCommandId?: string;
  /** Optional human-readable status detail. */
  message?: string;
  /** Optional normalized error code for retry and alerting decisions. */
  errorCode?: string;
  /** Whether the command can be safely retried by the control loop. */
  retryable?: boolean;
}

/**
 * Runtime adapter contract implemented by each hardware integration.
 */
export interface DeviceAdapter {
  /** Stable adapter ID, usually brand plus device role. */
  readonly adapterId: string;
  /** Vendor or platform name. */
  readonly brand: string;
  /** Normalized device category exposed by this adapter. */
  readonly kind: DeviceKind;
  /** Features this adapter can read or control. */
  readonly capabilities: DeviceCapability[];
  /** Read the latest normalized device state. */
  getState(signal?: AbortSignal): Promise<DeviceState>;
  /** Execute a normalized command against the underlying hardware API. */
  sendCommand(command: DeviceCommand, signal?: AbortSignal): Promise<CommandResult>;
  /** Fast capability guard used before dispatching commands. */
  supports(command: DeviceCommand): boolean;
}