import * as readline from "node:readline";
import * as fs from "node:fs";
import * as path from "node:path";

// ── Types ──────────────────────────────────────────────────────────────────────

export type KnownDevice =
  | "tesla_ev"
  | "givenergy_battery"
  | "solax_inverter"
  | "zappi_charger"
  | "octopus_smart_meter";

export interface OnboardingAnswers {
  name: string;
  email: string;
  devices: KnownDevice[];
  octopusApiKey: string;
  octopusAccountNumber: string;
  solcastApiKey: string;
  solcastResourceId: string;
  evDepartureTime: string;       // e.g. "07:30"
  evTargetChargePercent: string; // e.g. "80"
}

export interface OnboardingResult {
  answers: OnboardingAnswers;
  envLocalPath: string;
  envLocalContent: string;
}

// ── Readline abstraction (injectable for tests) ────────────────────────────────

export type AskFn = (question: string) => Promise<string>;

export function makeAskFn(rl: readline.Interface): AskFn {
  return (question: string) =>
    new Promise((resolve) => rl.question(question, (answer) => resolve(answer.trim())));
}

// ── Device menu ────────────────────────────────────────────────────────────────

const DEVICE_OPTIONS: { key: KnownDevice; label: string }[] = [
  { key: "tesla_ev", label: "Tesla EV" },
  { key: "givenergy_battery", label: "GivEnergy battery" },
  { key: "solax_inverter", label: "Solax inverter" },
  { key: "zappi_charger", label: "Zappi charger" },
  { key: "octopus_smart_meter", label: "Octopus smart meter" },
];

async function askDevices(ask: AskFn): Promise<KnownDevice[]> {
  console.log("\nWhich devices do you have? (enter numbers separated by commas, e.g. 1,3)");
  DEVICE_OPTIONS.forEach(({ label }, i) => {
    console.log(`  ${i + 1}. ${label}`);
  });

  const raw = await ask("Your devices: ");
  const indices = raw
    .split(",")
    .map((s) => parseInt(s.trim(), 10) - 1)
    .filter((i) => i >= 0 && i < DEVICE_OPTIONS.length);

  return [...new Set(indices)].map((i) => DEVICE_OPTIONS[i].key);
}

// ── .env.local writer ──────────────────────────────────────────────────────────

export function buildEnvLocalContent(answers: OnboardingAnswers): string {
  const lines: string[] = [
    "# Generated by Aveum beta onboarding — do not commit this file.",
    `# Set up for ${answers.name} on ${new Date().toISOString().slice(0, 10)}.`,
    "",
    "# ─── User ────────────────────────────────────────────────────────────────────",
    `AVEUM_USER_NAME=${answers.name}`,
    `AVEUM_NOTIFY_EMAIL=${answers.email}`,
    "",
    "# ─── Octopus Energy ──────────────────────────────────────────────────────────",
    `OCTOPUS_API_KEY=${answers.octopusApiKey}`,
    `OCTOPUS_ACCOUNT_NUMBER=${answers.octopusAccountNumber}`,
    "",
    "# ─── Devices ─────────────────────────────────────────────────────────────────",
    `AVEUM_DEVICES=${answers.devices.join(",")}`,
  ];

  if (answers.devices.includes("tesla_ev")) {
    lines.push(
      "",
      "# ─── Tesla EV ────────────────────────────────────────────────────────────────",
      `EV_DEPARTURE_TIME=${answers.evDepartureTime}`,
      `EV_TARGET_CHARGE_PERCENT=${answers.evTargetChargePercent}`,
    );
  }

  if (answers.devices.includes("givenergy_battery")) {
    lines.push(
      "",
      "# ─── GivEnergy ───────────────────────────────────────────────────────────────",
      "# Fill in after registering at https://givenergy.cloud",
      "GIVENERGY_API_KEY=",
      "GIVENERGY_INVERTER_SERIAL=",
    );
  }

  if (answers.devices.includes("solax_inverter")) {
    lines.push(
      "",
      "# ─── Solax ───────────────────────────────────────────────────────────────────",
      "# Fill in your Solax Cloud API token and SN",
      "SOLAX_API_KEY=",
      "SOLAX_INVERTER_SN=",
    );
  }

  if (answers.devices.includes("zappi_charger")) {
    lines.push(
      "",
      "# ─── Zappi ───────────────────────────────────────────────────────────────────",
      "# Fill in your myenergi hub serial and API key",
      "MYENERGI_HUB_SERIAL=",
      "MYENERGI_API_KEY=",
    );
  }

  if (answers.solcastApiKey) {
    lines.push(
      "",
      "# ─── Solcast Solar Forecast ─────────────────────────────────────────────────",
      `SOLCAST_API_KEY=${answers.solcastApiKey}`,
      `SOLCAST_RESOURCE_ID=${answers.solcastResourceId}`,
    );
  }

  lines.push("");
  return lines.join("\n");
}

// ── Core onboarding flow ───────────────────────────────────────────────────────

export async function runBetaOnboardingWithAsk(
  ask: AskFn,
  writeFileFn: (filePath: string, content: string) => void = fs.writeFileSync,
  projectRoot: string = process.cwd(),
): Promise<OnboardingResult> {
  console.log("\n╔══════════════════════════════════════════╗");
  console.log("║     Welcome to Aveum beta onboarding     ║");
  console.log("╚══════════════════════════════════════════╝\n");

  // Step 1 — name and email
  const name = await ask("Your name: ");
  const email = await ask("Your email address: ");

  // Step 2 — devices
  const devices = await askDevices(ask);
  if (devices.length === 0) {
    console.log("  (No devices selected — you can edit .env.local later.)");
  }

  // Step 3 — Octopus
  console.log("\n── Octopus Energy ───────────────────────────────────────");
  const octopusApiKey = await ask("Octopus API key (from octopus.energy/dashboard): ");
  const octopusAccountNumber = await ask("Octopus account number (e.g. A-1A2B3C4D): ");

  // Step 4 — Solcast (optional)
  console.log("\n── Solcast solar forecast (optional — press Enter to skip) ──");
  const solcastApiKey = await ask("Solcast API key: ");
  let solcastResourceId = "";
  if (solcastApiKey) {
    solcastResourceId = await ask("Solcast resource ID: ");
  }

  // Step 5 — EV departure (only when Tesla EV selected)
  let evDepartureTime = "";
  let evTargetChargePercent = "";
  if (devices.includes("tesla_ev")) {
    console.log("\n── Tesla EV ─────────────────────────────────────────────");
    evDepartureTime = await ask("Typical departure time (HH:MM, e.g. 07:30): ");
    evTargetChargePercent = await ask("Target charge percentage before departure (e.g. 80): ");
  }

  const answers: OnboardingAnswers = {
    name,
    email,
    devices,
    octopusApiKey,
    octopusAccountNumber,
    solcastApiKey,
    solcastResourceId,
    evDepartureTime,
    evTargetChargePercent,
  };

  // Step 6 — write .env.local
  const envLocalPath = path.join(projectRoot, ".env.local");
  const envLocalContent = buildEnvLocalContent(answers);
  writeFileFn(envLocalPath, envLocalContent);

  // Step 7 — summary
  console.log("\n──────────────────────────────────────────────────────────");
  console.log(`✓ Configuration written to ${envLocalPath}`);
  console.log(`\nAveum is set up for ${name}.`);
  console.log("Run npm run tesla:single-run to start your first optimisation cycle.\n");

  return { answers, envLocalPath, envLocalContent };
}

/**
 * Entry point wired to real readline + filesystem.
 * Called when the script is executed directly via `npm run onboard`.
 */
export async function runBetaOnboarding(): Promise<void> {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  try {
    await runBetaOnboardingWithAsk(makeAskFn(rl));
  } finally {
    rl.close();
  }
}

// Auto-run when executed directly (vite-node or node)
// Works for both ESM (`import.meta.url`) and CJS (`require.main`)
if (
  // ESM: vite-node sets import.meta.url
  (typeof import.meta !== "undefined" &&
    typeof process !== "undefined" &&
    process.argv[1] &&
    import.meta.url.endsWith(process.argv[1].replace(/\\/g, "/"))) ||
  // CJS fallback
  (typeof require !== "undefined" && typeof module !== "undefined" && require.main === module)
) {
  runBetaOnboarding().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
